blogs/urls.py
from django.urls import path
from .views import PublicationListView

urlpatterns = [
    path('', PublicationListView.as_view(), name='publications-list'),
]

django_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/models.py
from django.db import models

# Create your models here.
class publication(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
                                'auth.User',
                                on_delete=models.CASCADE
                              )
    
    def __str__(self):
        return self.title

blogs/views.py
from django.shortcuts import render
from .models import publication
from django.views.generic import ListView
# Create your views here.


class PublicationListView(ListView):
    model = publication
    template_name = 'home.html'

    

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>publication list</title>
</head>
<body>

    <h1> publicaiones</h1>

    {% for post in publication_list %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.author }} on {{ post.published_date }} </p>
    {% endfor %}
     
</body>
</html>